name: "BuildArm64 And Release"

on:
  push:
    branches:
      - build-arm64

jobs:
  buildArm64-and-upload:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.7

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: "Get package info"
        id: package-info
        uses: luizfelipelaviola/get-package-info@v1
        with:
          path: ./packages/mitmproxy

      - name: "Print"
        run: |
          echo "version = ${{ steps.package-info.outputs.version }}";
          echo "github.ref_type = ${{ github.ref_type }}";
          echo "github.ref = ${{ github.ref }}";
          echo "github.ref_name = ${{ github.ref_name }}";
          echo "github.workspace = ${{ github.workspace }}";
          echo "NODE_AUTH_TOKEN = ${{ NODE_AUTH_TOKEN }}";

      - name: "Set up QEMU"
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Build on 'arm64v8/ubuntu:20.04' OS"
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace:rw --workdir=/workspace \
            -v /home/runner/work/_temp:/home/runner/work/_temp:rw \
            -e NPM_CONFIG_USERCONFIG=/home/runner/work/_temp/.npmrc
            -e NODE_AUTH_TOKEN=${{ NODE_AUTH_TOKEN }}
            --platform linux/arm64 arm64v8/ubuntu:20.04 \
            bash -exc  'apt-get update && \
                        apt-get install curl -y && \
                        curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
                        apt-get install -y nodejs gcc g++ make && \
                        apt update && \
                        apt install python3 -y && \
                        npm config set userconfig "/home/runner/work/_temp/.npmrc" && \
                        npm config set "always-auth" false && \
                        npm config set "@docmirror:registry" https://npm.pkg.github.com && \
                        npm config set "//npm.pkg.github.com/:_authToken" ${{ NODE_AUTH_TOKEN }} && \
                        npm config list && \
                        npm install -g lerna@6 && \
                        node -p "process.arch" && \
                        lerna -v && \
                        npm -v && \
                        ls -lah && \
                        lerna bootstrap && \
                        cd packages/gui && \
                        ls -lah && \
                        npm run electron:build && \
                        cd dist_electron && \
                        ls -lah && \
                        cd ../../../ && \
                        ls -lah'

      - name: "Upload DevSidecar-${{ steps.package-info.outputs.version }}-node${{ matrix.node }}.deb - Ubuntu"
        uses: actions/upload-artifact@v4.4.0
        with:
          path: packages/gui/dist_electron/DevSidecar-${{ steps.package-info.outputs.version }}.deb
          name: "DevSidecar-${{ steps.package-info.outputs.version }}-node${{ matrix.node }}.deb"
          if-no-files-found: error
      - name: "Upload DevSidecar-${{ steps.package-info.outputs.version }}-node${{ matrix.node }}.AppImage - Ubuntu"
        uses: actions/upload-artifact@v4.4.0
        with:
          path: packages/gui/dist_electron/DevSidecar-${{ steps.package-info.outputs.version }}.AppImage
          name: "DevSidecar-${{ steps.package-info.outputs.version }}-node${{ matrix.node }}.AppImage"
          if-no-files-found: error
